### ISSUE TITLE
Allow operator to watch the own namespace only

### ISSUE THREAD

**Issue by jurim76** [ktsstudio/mirrors#8]
I want to copy the secret "secret1" from namespace "ns1" to namespaces "ns2","ns3" and copy the secret "secret2" from namespace "ns3" to namespace "ns4"
According to documentation `Security note: mirrors specifically does not allow copying a secret from arbitrary namespace, only from the namespace where a SecretMirror is deployed.`
In this case I need to install two operators - in "ns1" namespace and in "ns3" namespace. After the setup, these two operators start to watch all namespaces for `secretmirrors.mirrors.kts.studio` CR and operator in "ns1" namespace found secret "secret1" and copies to namespace "ns2", "ns3". Operator in namespace "ns3" found the `secretmirrors.mirrors.kts.studio` CR for operator in namespace "ns1", found the same secret "secret1" in own namespace "ns3" and start to monitor this secret too.

The operator congifuration should allow to monitor all namespaces or only own namespace.

**Comment by igorcoding** [comment]
Hi! 
There was a slight misunderstanding. You'd need to install operator only once (say in `mirros-system` namespace). And then for your case:
1. Deploy a Secret `secret1` in `ns1` and Secret `secret2` to `ns3`
2. Then deploy a SecretMirror `mirror-secret2` in `ns1` namespace with the following spec:
```yaml
apiVersion: mirrors.kts.studio/v1alpha2
kind: SecretMirror
metadata:
  name: mirror-secret1
  namespace: ns1
spec:
  source:
    name: secret1
  destination:
    namespaces:
      - ns2
      - ns3
```
3. Then deploy a SecretMirror `mirror-secret2` in `ns3` namespace with the following spec:
```yaml
apiVersion: mirrors.kts.studio/v1alpha2
kind: SecretMirror
metadata:
  name: mirror-secret2
  namespace: ns3
spec:
  source:
    name: secret2
  destination:
    namespaces:
      - ns4
```

That security note is only about the case when the secret is located in the different namespace than the SecretMirror resource itself - this is not possible. SecretMirror can find only secrets in the namespace where they are created (not the operator, but the CR itself)
